### ISSUE TITLE
关于最后的结果

### ISSUE THREAD

**Issue by mliwang** [guoday/Tencent2020_Rank1st#1]
请问，最终要预测的年龄看起来是个连续的整数，但是看模型最后输出的是20个类别的概率，请问这是怎么对应上的

**Comment by guoday** [comment]
> 请问，最终要预测的年龄看起来是个连续的整数，但是看模型最后输出的是20个类别的概率，请问这是怎么对应上的

请看该图https://github.com/guoday/Tencent2020_Rank1st/blob/master/picture/output.png，2中给了求年龄的概率，最后取argmax作为输出
