### ISSUE TITLE
vocab_dim_v1

### ISSUE THREAD

**Issue by 256785** [guoday/Tencent2020_Rank1st#12]
请教一下，vocab_dim_v1=64是什么维度

**Comment by guoday** [comment]
> 请教一下，vocab_dim_v1=64是什么维度

Bert的embedding

**Comment by 256785** [comment]
在bert的模型里
inputs_embedding=self.text_embeddings(inputs_ids).view(inputs.size(0),inputs.size(1),-1)

self.text_embeddings(inputs_ids)之后维数是【128，8，64】  而 inputs.size(0)是128，inputs.size(1)是1024 这里应该无法进行view运算呀？请教一下，是我哪里的维数理解错了吗

**Comment by guoday** [comment]
> 在bert的模型里
> inputs_embedding=self.text_embeddings(inputs_ids).view(inputs.size(0),inputs.size(1),-1)
> 
> self.text_embeddings(inputs_ids)之后维数是【128，8，64】 而 inputs.size(0)是128，inputs.size(1)是1024 这里应该无法进行view运算呀？请教一下，是我哪里的维数理解错了吗

是[bacth_size,128,8,64]
