### ISSUE TITLE
预训练词向量频次过滤问题

### ISSUE THREAD

**Issue by shexuan** [guoday/Tencent2020_Rank1st#14]
您好，我看 `src/w2v.py`预训练中没有通过词频对出现的各种id进行过滤，直接`min_count=1`，请问这是因为`min_count=1`的结果最好还是为了与后续bert训练保持词表一致？或者还是其他的原因？然后请教下这个`min_count`参数的设置有什么经验吗？谢谢！！！

**Comment by guoday** [comment]
> 您好，我看 `src/w2v.py`预训练中没有通过词频对出现的各种id进行过滤，直接`min_count=1`，请问这是因为`min_count=1`的结果最好还是为了与后续bert训练保持词表一致？或者还是其他的原因？然后请教下这个`min_count`参数的设置有什么经验吗？谢谢！！！

w2v不需要过滤，这样每个id都有vector，对冷启动会好

**Comment by shexuan** [comment]
> > 您好，我看 `src/w2v.py`预训练中没有通过词频对出现的各种id进行过滤，直接`min_count=1`，请问这是因为`min_count=1`的结果最好还是为了与后续bert训练保持词表一致？或者还是其他的原因？然后请教下这个`min_count`参数的设置有什么经验吗？谢谢！！！
> 
> w2v不需要过滤，这样每个id都有vector，对冷启动会好

哦哦好的，我还想着不过滤会不会词表过大了导致后面模型参数太多，毕竟几百万。非常感谢大佬的快速回复！！！

**Comment by guoday** [comment]
> > > 您好，我看 `src/w2v.py`预训练中没有通过词频对出现的各种id进行过滤，直接`min_count=1`，请问这是因为`min_count=1`的结果最好还是为了与后续bert训练保持词表一致？或者还是其他的原因？然后请教下这个`min_count`参数的设置有什么经验吗？谢谢！！！
> > 
> > 
> > w2v不需要过滤，这样每个id都有vector，对冷启动会好
> 
> 哦哦好的，我还想着不过滤会不会词表过大了导致后面模型参数太多，毕竟几百万。非常感谢大佬的快速回复！！！

因为放在cpu，并且不训练的，所以还好
