### ISSUE TITLE
请问模型config中的vocab_size=5表示什么意思？

### ISSUE THREAD

**Issue by shexuan** [guoday/Tencent2020_Rank1st#16]
我看到在预训练和训练模型的encoder中都有`config.vocab_size=5`这个参数，请问这个表示什么意思和什么作用？在后面找了很久也没有找到用到这个的地方，而且输入encoder的直接是embeding向量吧，所以也没有用到bert encoder里面的embeding。那么这个vocab_size似乎是没用到？

**Comment by guoday** [comment]
因为没用到bert的embedding，所以才设置成5。默认为50000，浪费空间，所以就设置一个很小的值，设置为vocab_size=1也行

**Comment by shexuan** [comment]
> 因为没用到bert的embedding，所以才设置成5。默认为50000，浪费空间，所以就设置一个很小的值，设置为vocab_size=1也行

好的  非常感谢大佬
