### ISSUE TITLE
尊敬的作者，请问提供的bert-small是否经过预训练？

### ISSUE THREAD

**Issue by greenary-John** [guoday/Tencent2020_Rank1st#18]
非常感谢您愿意开源，感谢您精彩的工作，请问您的bert-small是否经过预训练(因为您的注解里面提到bert-small需要经过预训练)
不知道能否浪费您宝贵的时间，麻烦您发送一下经过预训练的bert-small，菜鸡的配置比较低（内存比较64G，显存24G）glmyx@qq.com
再次感谢您出色的工作
另能否小声提个建议，您上传资源能否选择国内的运营商，因为Google drive需要科学上网

**Comment by guoday** [comment]
已经预训练完成的,已发送到你邮箱
