### ISSUE TITLE
Word2Vector和BERT权重必须一致是什么意思

### ISSUE THREAD

**Issue by Flyfoxs** [guoday/Tencent2020_Rank1st#2]
恭喜大佬再次喜提冠军, Word2Vector和BERT权重必须一致是什么意思?

---
这里提供两种方式获得预训练权重: 重新预训练或下载预训练好的权重

注: **Word2Vector和BERT权重必须一致**，即要么全部重新预训练，要么全部下载

**Comment by guoday** [comment]
> 恭喜大佬再次喜提冠军, Word2Vector和BERT权重必须一致是什么意思?
> 
> 这里提供两种方式获得预训练权重: 重新预训练或下载预训练好的权重
> 
> 注: **Word2Vector和BERT权重必须一致**，即要么全部重新预训练，要么全部下载

谢谢。因为我分阶段训练，先训练W2V再预训练BERT，因此需要W2V和BERT保持一致，即BERT使用哪一套W2V预训练的，就需要用哪一套W2V。如果你们自己训练W2V，然后又下载我的BERT，那么就会不一致，因为我的BERT并不是使用你自己训练的W2V来预训练的，因此你自己只能重新预训练BERT。这就是为什么我说“W2V和BERT要么全部下载使用，要么自己重新训练”

**Comment by Flyfoxs** [comment]
👍
