### ISSUE TITLE
有关模型细节的几个疑问

### ISSUE THREAD

**Issue by Mandule** [guoday/Tencent2020_Rank1st#3]
有几个疑问希望郭大能答疑解惑一下！

1. Bert预训练时产生的输入端词典和输出端词典都是至多保留10W个ID，并且在分类时也是使用的相同词典，是不是可以理解为只使用了高频的ID进行预训练和分类。

2. Bert预训练时，MASK、PAD、UNK 所对应的 embedding 是否都是 全0 。如果是的话，这三个 special token 成为等价的话，会不会影响预训练。

3. Bert预训练时，输入端拼接了 word2vec 和 一个 16 维的 embeddings，这个16维的embeddings 是起到一个什么作用。

**Comment by guoday** [comment]
> 有几个疑问希望郭大能答疑解惑一下！
> 
> 1. Bert预训练时产生的输入端词典和输出端词典都是至多保留10W个ID，并且在分类时也是使用的相同词典，是不是可以理解为只使用了高频的ID进行预训练和分类。
> 2. Bert预训练时，MASK、PAD、UNK 所对应的 embedding 是否都是 全0 。如果是的话，这三个 special token 成为等价的话，会不会影响预训练。
> 3. Bert预训练时，输入端拼接了 word2vec 和 一个 16 维的 embeddings，这个16维的embeddings 是起到一个什么作用。

1.输入端影响其实不大，主要还是输出端，确实可以理解为预测高频的ID
2.首先PAD这个token没啥用，因为我attention的时候mask掉了，所以PAD对应什么embedding都无所谓，因为被忽略。MASK我是用了0向量的，既然PAD是无效的，其实0向量就被MASK专有了。UNK我只有可学习的16维embedding才有，word2vec是没有unk的。因此来说MASK和UNK是不一样的，MASK是0向量，UNK的16维是可学习的，w2v是没有unk，而PAD是被忽略的。
3.这16维embedding其实就是为了随机初始化，能够随着BERT学习，但提升不是很大，大概1个千分点。
