### ISSUE TITLE
弱问下，PPT图中的 广告受众人群的性别年龄分布，在预测阶段怎么得到？

### ISSUE THREAD

**Issue by guotong1988** [guoday/Tencent2020_Rank1st#6]
@guoday 多谢多谢

**Comment by guoday** [comment]
> @guoday 多谢多谢

使用训练集的所有数据作为种子人群

**Comment by guotong1988** [comment]
弱问下 种子人群 的概念？

**Comment by guoday** [comment]
> 弱问下 种子人群 的概念？

种子人群就是用来统计广告的性别年龄分布，然后赋值给另一个人群的。比如测试集就不能作为种子人群，因为没有性别年龄信息

**Comment by guotong1988** [comment]
感谢回复，直接赋值给另一人群，不是相当于训练和预测阶段这个特征一样吗？没有泛化的感觉？

**Comment by guoday** [comment]
> 感谢回复，
> 
> 直接赋值给另一人群，不是相当于训练和预测阶段这个特征一样吗？没有泛化的感觉？

不一样，训练的时候分五份，1234→5，1235→4，1245→3,1345→2,2345→1，因此只有80%的训练集统计，给另外的20%。预测的时候取100%的训练集给测试集

**Comment by guotong1988** [comment]
这个做法提升多少？感谢！

**Comment by guoday** [comment]
> 这个做法提升多少？感谢！

提升特别大，大概4个千分点，也是获胜的关键之一。你可以看我们ppt上分情况，有提到这个fusion layer

**Comment by guotong1988** [comment]
模型本身居然捕获不到这些分布信息

**Comment by guoday** [comment]
> 模型本身居然捕获不到这些分布信息

主要广告比较稀疏，通过统计的方法会更好一些。如果广告特别稠密，比如只有1万个id，那么这方法就没啥用了

**Comment by guotong1988** [comment]
哦哦，刚想问其他分类任务是否能这样把label分布加进去

**Comment by juzstu** [comment]
想问下，这个和target encoding有啥区别？

**Comment by guoday** [comment]
> 想问下，这个和target encoding有啥区别？

没区别
