### ISSUE TITLE
弱问下，PPT图中的 用户点击序列 具体？

### ISSUE THREAD

**Issue by guotong1988** [guoday/Tencent2020_Rank1st#7]
被点击的广告的信息(素材 id、广告 id、产品 id、产品类目 id、广告主 id、广告主行业 id 等)

这么多id用哪个？怎么结合？

@guoday 多谢多谢

**Comment by guoday** [comment]
> 被点击的广告的信息(素材 id、广告 id、产品 id、产品类目 id、广告主 id、广告主行业 id 等)
> 
> 这么多id用哪个？怎么结合？
> 
> @guoday 多谢多谢

每个id都会有embedding（每个128维），拼接起来总共1028维，最后经过一个全连接层降到512维
