### ISSUE TITLE
请问其他属性id是如何融入广告id的？

### ISSUE THREAD

**Issue by 256785** [guoday/Tencent2020_Rank1st#8]
在进行w2v的时候是分别根据序列进行embeding得到128维向量。
请教一下，后续是如何融入到同一空间的？

**Comment by guoday** [comment]
> 在进行w2v的时候是分别根据序列进行embeding得到128维向量。
> 
> 请教一下，后续是如何融入到同一空间的？

拼接起来经过全连接层，降维到512维

**Comment by 256785** [comment]
在预训练bert的时候，是不同的id分别做成序列进行encoding吗？

**Comment by guoday** [comment]
> 在预训练bert的时候，是不同的id分别做成序列进行encoding吗？
不是，所有id的embedding拼接起来，经过全连接层，得到512维的表示，只有一个序列

**Comment by hsaigei** [comment]
不太理解, 能不能给段的代码呀?谢谢

**Comment by guoday** [comment]
> 不太理解, 能不能给段的代码呀?谢谢

请看src/data_loader.py谢谢
